core/urls.py
from django.contrib.staticfiles.views import serve
from django.urls import path, re_path
from .views import *

app_name = 'core'

urlpatterns = [
    path('uploadwithcsv/', add_items, name='upload'),
    path('orders/', orders, name='orders'),
    path('', home, name='home'),
    path('profile', profile, name='profile'),
    path('shop/<str:ctg>/<str:ctg2>/<str:ctg3>', home1, name='shop'),
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('order-summary/', order_summary, name='order-summary'),
    path('order-clear/', clear_cart, name='clear_cart'),
    path('product/<slug>/', detail, name='product'),
    path('product/next/<slug>/', detail_next, name='product_next'),
    path('product/prev/<slug>/', detail_prev, name='product_prev'),
    path('add-to-cart/<slug>', add_to_cart, name='add-to-cart'),
    path('add-to-cart1', add_to_cart1, name='add-to-cart1'),
    path('add-coupon/', AddCouponView.as_view(), name='add-coupon'),
    path('remove-from-cart/<slug>/', remove_from_cart, name='remove-from-cart'),
    path('remove-item-from-cart/<slug>/', remove_single_item_from_cart,
         name='remove-single-item-from-cart'),
    # path('payment/<payment_option>/', PaymentView.as_view(), name='payment'),
    path('successPayment/', SuccesPayment, name='success'),
    path('request-refund/', RequestRefundView.as_view(), name='request-refund'),
]

templates/carousel.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <title>599.kz</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat&family=Rubik&display=swap" rel="stylesheet">
    <link href="{% static 'css/style4.css'%}" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/newstyle.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/slider1.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/lightslider.css' %}" />
    <script src="{% static 'js/jquery-3.5.1.js' %}" ></script>
    <script src="{% static 'js/lightslider.js' %}" ></script>
    <style>
        html{
            scroll-behavior:smooth
        }
        .mobile{
            padding-top: 500px;
            padding-left: 52px;
            height: 750px;
            width: 100%;
            background-image: url("{% static 'img/mobile.png' %}");
            background-size: cover;
        }
        .mobile .texts{
            scroll-behavior:smooth;
            color: black;
            font-family: 'Montserrat', sans-serif;
            padding: 15px;
            font-size: 16px;
            background-color: #FFEA00;
        }
    </style>
</head>
<body>
{% include "navbar.html" %}
    <div class="main d-none d-lg-block">
        <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel" style="width: 100%; margin-bottom: 50px;">
        <ol class="carousel-indicators">
          <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
          <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
          <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
          <li data-target="#carouselExampleIndicators" data-slide-to="3"></li>
          <li data-target="#carouselExampleIndicators" data-slide-to="4"></li>
          <li data-target="#carouselExampleIndicators" data-slide-to="5"></li>
          <li data-target="#carouselExampleIndicators" data-slide-to="6"></li>

        </ol>
        <div class="carousel-inner" style="height: 750px;">
            <div class="carousel-item active" style="background: url({% static 'img/7.png' %}); height: 100%; background-repeat: no-repeat; background-size: cover; background-position: center;">
          </div>
          <div class="carousel-item" style="background: url({% static 'img/2.png' %}); height: 100%; background-repeat: no-repeat; background-size: cover; background-position: center;">
          </div>
          <div class="carousel-item" style="background: url({% static 'img/3.png' %}); height: 100%; background-repeat: no-repeat; background-size: cover; background-position: center;">
          </div>
          <div class="carousel-item" style="background: url({% static 'img/3.png' %}); height: 100%; background-repeat: no-repeat; background-size: cover; background-position: top;">

          </div>
            <div class="carousel-item" style="background: url({% static 'img/4.png' %}); height: 100%; background-repeat: no-repeat; background-size: cover; background-position: top;">

          </div>
            <div class="carousel-item" style="background: url({% static 'img/5.png' %}); height: 100%; background-repeat: no-repeat; background-size: cover; background-position: top;">

          </div>
            <div class="carousel-item" style="background: url({% static 'img/6.png' %}); height: 100%; background-repeat: no-repeat; background-size: cover; background-position: top;">

          </div>
        </div>
        <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>
    </div>
{#        <a>Закупиться сейчас</a>#}
    </div>
    <div class="mobile d-lg-none d-md-none d-sm-block">
        <a href="#feat" class="texts">Закупиться сейчас</a>
    </div>
    <div class="characteristics">
		<div class="container">
			<div class="row">

				<!-- Char. Item -->
				<div class="col-lg-3 col-md-6 char_col">

					<div class="char_item d-flex flex-row align-items-center justify-content-start">
						<div class="char_icon"><img src="{% static 'img/char_1.png'%}" alt=""></div>
						<div class="char_content">
							<div class="char_title">Быстрая доставка</div>
{#							<div class="char_subtitle">from $50</div>#}
						</div>
					</div>
				</div>

				<!-- Char. Item -->
				<div class="col-lg-3 col-md-6 char_col">

					<div class="char_item d-flex flex-row align-items-center justify-content-start">
						<div class="char_icon"><img src="{% static 'img/char_2.png' %}" alt=""></div>
						<div class="char_content">
							<div class="char_title">Широкий ассортимент</div>
{#							<div class="char_subtitle">from $50</div>#}
						</div>
					</div>
				</div>

				<!-- Char. Item -->
				<div class="col-lg-3 col-md-6 char_col">

					<div class="char_item d-flex flex-row align-items-center justify-content-start">
						<div class="char_icon"><img src="{% static 'img/char_3.png'%}" alt=""></div>
						<div class="char_content">
							<div class="char_title">Удобство и доступность</div>
{#							<div class="char_subtitle"></div>#}
						</div>
					</div>
				</div>

				<!-- Char. Item -->
				<div class="col-lg-3 col-md-6 char_col">

					<div class="char_item d-flex flex-row align-items-center justify-content-start">
						<div class="char_icon"><img src="{% static 'img/char_4.png' %}" alt=""></div>
						<div class="char_content">
							<div class="char_title">Низкие цены</div>
{#							<div class="char_subtitle">from $50</div>#}
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
    	<div class="new_arrivals" id="feat">
		<div class="container">
			<div class="row">
				<div class="col-12">
					<div class="tabbed_container">
						<div class="tabs clearfix tabs-right">
							<ul class="clearfix">
								<li class="active">Рекомендованные</li>
							</ul>
							<div class="tabs_line"><span></span></div>
						</div>
						<div class="row">
							<div class="col-lg-12" style="z-index:1;">

								<!-- Product Panel -->
								<div class="product_panel panel active">
									<div class="arrivals_slider slider">

										<!-- Slider Item -->
                                        {% for item in items %}
										<div class="arrivals_slider_item col-lg-12 col-md-4 col-sm-6 pb-1 col-6">
											<div class="product_item is_new d-flex flex-column align-items-center justify-content-center text-center">
												<div class="product_image d-flex flex-column align-items-center justify-content-center"><img src="{{ item.image }}" height="100%" alt=""></div>
												<div class="product_content">
													<div class="product_price">₸{{ item.price }}</div>
													<div class="product_name"><div><a href="{% url 'core:product' item.slug %}">{{ item.title }}</a></div></div>
													<div class="product_extras">
                                                        {% if request.user.is_authenticated %}
														   <button class="product_cart_button" id="add_to_card" value="{{ item.slug }}" type="button">В корзину</button>
                                                        {% else %}
                                                            <a href="{% url 'account_login' %}"><button class="product_cart_button" type="button">В корзину</button></a>
                                                        {% endif %}
													</div>
												</div>
												<div class="product_fav"><i class="fas fa-heart"></i></div>
												<ul class="product_marks">
													<li class="product_mark product_discount">-25%</li>
													<li class="product_mark product_new">new</li>
												</ul>
											</div>
										</div>
                                        {% endfor %}
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        </div>
{#<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.carousel.min.css">#}
{#<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.theme.default.css">#}
{#<script src="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.2.1/owl.carousel.js"></script>#}
{% include "footer.html" %}
</body>
    <script type="text/javascript">
    const buttons = document.querySelectorAll('button[type="button"]');
    console.log(buttons)
    for(let i = 0; i < buttons.length ; i++) {
        if(buttons[i].id == 'add_to_card'){
            console.log(buttons[i]['value'])
            buttons[i].addEventListener('click',function(e){
                e.preventDefault();
                $.ajax({
                    type:'POST',
                    url:'{% url "core:add-to-cart1" %}',
                    data:
                    {
                        slug:buttons[i]['value'],
                        csrfmiddlewaretoken:$('input[name=csrfmiddlewaretoken]').val()
                    },
                    dataType:'json',
                    success:function(){
                        let p = document.getElementById('number');
                        console.log(p)
                        alert("Добавлено в корзину " + buttons[i]['name']);
                    }
                })
            });
        }
    }
</script>
</html>

templates/carousel_search.html
{% load static %}
<style>
    #img-c{
        height: 230px;
        line-height: 230px;
        margin-bottom: 10px;
        display: flex;
    }
    .img{
        display: inline-block;
        vertical-align: middle;
        max-width: 100%;
        max-height: 100%;
    }
    @media screen  and (max-width: 760px) {
        #img-c {
            height: 160px;
            line-height: 160px;
        }
    }
</style>
<div class="container-fluid pt-5 pb-3" style="width: 95%">
<a class="text-decoration-none text-center"><h2 class="text-uppercase mx-xl-5 mb-4 justify-content-center bg-default" >Результаты поиска</h2></a>
<div class="row px-xl-5">
    {% for item in searching_list %}
        <div class="col-lg-2 col-md-4 col-sm-6 pb-1 col-6">
            <div class="product-item bg-light mb-4">
                <div class="product-img position-relative overflow-hidden justify-content-around" id="img-c">
                    <a href="{{ item.get_absolute_url }}">
                        <img class="img" src="{{ item.image.url }}" alt="">
                    </a>
                </div>
                <div class="text-center pt-2" style="word-break: break-word;">
                    <a class="text-decoration-none" href="{{ item.get_absolute_url }}"><p style="color: black; min-height: 36px; max-height: 36px; font-size: 12px">{{ item.title }}</p></a>

                    <div class="d-flex align-items-center justify-content-center" style="margin-top: 20px">
                        <p style="font-size: 12px;color: black">{{ item.get_price }}₸</p>
                    </div>
                </div>
                <div class="d-flex align-items-center justify-content-center" style="height: 40px;">
                    <button style="border-radius: 15px; color: dodgerblue" class="btn btn-outline-dark" id="add_to_card"  value="{{ item.slug }}" type="button"><i class="fa fa-shopping-cart bg-transparent" style="color: dodgerblue"></i></button>
                </div>
            </div>
        </div>
    {% endfor %}
</div>
    </div>

templates/order_snippet.html
<div class="col-md-12 mb-4">
    <h4 class="d-flex justify-content-between align-items-center mb-3">
    <span class="text-muted">Ваш заказ</span>
    <span class="badge badge-secondary badge-pill">{{ order.items.count }}</span>
    </h4>
    <ul class="list-group mb-3 z-depth-1">
    {% for order_item in order.items.all %}
    <li class="list-group-item d-flex justify-content-between lh-condensed">
        <div>
        <h6 class="my-0">{{ order_item.quantity }} x {{ order_item.item.title}}</h6>
        <small class="text-muted">{{ order_item.item.description}}</small>
        </div>
        <span class="text-muted">₸{{ order_item.get_final_price }}</span>
    </li>
    {% endfor %}
    {% if order.coupon %}
    <li class="list-group-item d-flex justify-content-between bg-light">
        <div class="text-success">
        <h6 class="my-0">Promo code</h6>
        <small>{{ order.coupon.code }}</small>
        </div>
        <span class="text-success">-₸{{ order.coupon.amount }}</span>
    </li>
    {% endif %}
    <li class="list-group-item d-flex justify-content-between">
        <span>Сумма к оплате</span>
        <strong>₸{{ order.get_total }}</strong>
    </li>
    </ul>

    {% if DISPLAY_COUPON_FORM %}
    <form class="card p-2" action="{% url 'core:add-coupon' %}" method="POST">
        {% csrf_token %}
        <div class="input-group">
            {{ couponform.code }}
            <div class="input-group-append">
            <button class="btn btn-secondary btn-md waves-effect m-0" type="submit">Применить</button>
            </div>
        </div>
    </form>
    {% endif %}

</div>

templates/order_summary.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<meta http-equiv="content-type" content="text/html;charset=UTF-8" />
<head>
<title>Cart</title>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="description" content="OneTech shop project">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
<link rel="stylesheet" type="text/css" href="{% static 'styles/bootstrap4/bootstrap.min.css' %}">
<link href="{% static 'plugins/fontawesome-free-5.0.1/css/fontawesome-all.css' %}" rel="stylesheet" type="text/css">
<link rel="stylesheet" type="text/css" href="{% static 'styles/cart_styles.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'styles/cart_responsive.css' %}">

</head>

<body>

<div class="super_container">
    {% include 'navbar.html' %}

	<div class="cart_section" style="">
		<div class="container">
			<div class="row">
				<div class="col-lg-10 offset-lg-1">
					<div class="cart_container">
						<div class="cart_title">Корзина</div>
						<div class="cart_items">
                            {% for item in order.items.all %}
							<ul class="cart_list">
								<li class="cart_item clearfix">
									<div class="cart_item_image"><img src="{{ item.item.image.url }}" alt=""></div>
									<div class="cart_item_info d-flex flex-md-row flex-column justify-content-between">
										<div class="cart_item_name cart_info_col">
											<div class="cart_item_title">Название</div>
											<div class="cart_item_text">{{ item.item.title }}</div>
										</div>
										<div class="cart_item_color cart_info_col">
											<div class="cart_item_title">Цвет</div>
											<div class="cart_item_text"><span style="background-color:{{ item.color.encode }};"></span>{{ item.color.title }}</div>
										</div>
										<div class="cart_item_quantity cart_info_col">
											<div class="cart_item_title">Количество</div>
											<div class="cart_item_text">
                                                <a href="{% url 'core:remove-single-item-from-cart' item.item.slug %}" style="font-size: 12px"><i class="fas fa-minus mr-2"></i></a>
                                                {{ item.quantity }}
                                                <a href="{% url 'core:add-to-cart' item.item.slug %}" style="font-size: 12px"><i class="fas fa-plus ml-2"></i></a>
                                            </div>
										</div>
										<div class="cart_item_price cart_info_col">
											<div class="cart_item_title">Цена</div>
											<div class="cart_item_text">₸{{ item.item.get_price }}</div>
										</div>
										<div class="cart_item_total cart_info_col">
											<div class="cart_item_title">Сумма</div>
											<div class="cart_item_text">₸{{ item.get_total_item_price }}</div>
										</div>
									</div>
								</li>
							</ul>
                            {% endfor %}
						</div>

						<!-- Order Total -->
						<div class="order_total">
							<div class="order_total_content text-md-right">
								<div class="order_total_title">Общая сумма:</div>
								<div class="order_total_amount">₸{{ order.get_total }}</div>
							</div>
						</div>

						<div class="cart_buttons">
							<a class="button cart_button_checkout" href='/'>Назад к товарам</a>
							<a class="button cart_button_checkout" href='/checkout/'>Перейти к оплате</a>
                            <a class="button cart_button_checkout" style="background-color: red" href='/order-clear'>Очистить корзину</a>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>

	<!-- Newsletter -->

	<div class="newsletter">
		<div class="container">
			<div class="row">
				<div class="col">
					<div class="newsletter_container d-flex flex-lg-row flex-column align-items-lg-center align-items-center justify-content-lg-start justify-content-center">
						<div class="newsletter_title_container">
							<div class="newsletter_icon"><img src="{% static 'img/send.png' %}" alt=""></div>
							<div class="newsletter_title">Sign up for Newsletter</div>
							<div class="newsletter_text"><p>...and receive %20 coupon for first shopping.</p></div>
						</div>
						<div class="newsletter_content clearfix">
							<form action="#" class="newsletter_form">
								<input type="email" class="newsletter_input" required="required" placeholder="Enter your email address">
								<button class="newsletter_button">Subscribe</button>
							</form>
							<div class="newsletter_unsubscribe_link"><a href="#">unsubscribe</a></div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>

	<!-- Footer -->

	<footer class="footer">
		<div class="container">
			<div class="row">

				<div class="col-lg-3 footer_col">
					<div class="footer_column footer_contact">
						<div class="logo_container">
							<div class="logo"><a href="#">OneTech</a></div>
						</div>
						<div class="footer_title">Got Question? Call Us 24/7</div>
						<div class="footer_phone">+38 068 005 3570</div>
						<div class="footer_contact_text">
							<p>17 Princess Road, London</p>
							<p>Grester London NW18JR, UK</p>
						</div>
						<div class="footer_social">
							<ul>
								<li><a href="#"><i class="fab fa-facebook-f"></i></a></li>
								<li><a href="#"><i class="fab fa-twitter"></i></a></li>
								<li><a href="#"><i class="fab fa-youtube"></i></a></li>
								<li><a href="#"><i class="fab fa-google"></i></a></li>
								<li><a href="#"><i class="fab fa-vimeo-v"></i></a></li>
							</ul>
						</div>
					</div>
				</div>

				<div class="col-lg-2 offset-lg-2">
					<div class="footer_column">
						<div class="footer_title">Find it Fast</div>
						<ul class="footer_list">
							<li><a href="#">Computers & Laptops</a></li>
							<li><a href="#">Cameras & Photos</a></li>
							<li><a href="#">Hardware</a></li>
							<li><a href="#">Smartphones & Tablets</a></li>
							<li><a href="#">TV & Audio</a></li>
						</ul>
						<div class="footer_subtitle">Gadgets</div>
						<ul class="footer_list">
							<li><a href="#">Car Electronics</a></li>
						</ul>
					</div>
				</div>

				<div class="col-lg-2">
					<div class="footer_column">
						<ul class="footer_list footer_list_2">
							<li><a href="#">Video Games & Consoles</a></li>
							<li><a href="#">Accessories</a></li>
							<li><a href="#">Cameras & Photos</a></li>
							<li><a href="#">Hardware</a></li>
							<li><a href="#">Computers & Laptops</a></li>
						</ul>
					</div>
				</div>

				<div class="col-lg-2">
					<div class="footer_column">
						<div class="footer_title">Customer Care</div>
						<ul class="footer_list">
							<li><a href="#">My Account</a></li>
							<li><a href="#">Order Tracking</a></li>
							<li><a href="#">Wish List</a></li>
							<li><a href="#">Customer Services</a></li>
							<li><a href="#">Returns / Exchange</a></li>
							<li><a href="#">FAQs</a></li>
							<li><a href="#">Product Support</a></li>
						</ul>
					</div>
				</div>

			</div>
		</div>
	</footer>

	<!-- Copyright -->

	<div class="copyright">
		<div class="container">
			<div class="row">
				<div class="col">

					<div class="copyright_container d-flex flex-sm-row flex-column align-items-center justify-content-start">
						<div class="copyright_content">
Copyright &copy;<script data-cfasync="false" src="../../../cdn-cgi/scripts/5c5dd728/cloudflare-static/email-decode.min.js"></script><script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart" aria-hidden="true"></i> by <a href="https://templatespoint.net/" target="_blank">TemplatesPoint</a>
</div>
						<div class="logos ml-sm-auto">
							<ul class="logos_list">
								<li><a href="#"><img src="{% static 'img/logos_1.png'%}" alt=""></a></li>
								<li><a href="#"><img src="{% static 'img/logos_2.png' %}" alt=""></a></li>
								<li><a href="#"><img src="{% static 'img/logos_3.png' %}" alt=""></a></li>
								<li><a href="#"><img src="{% static 'img/logos_4.png'%}" alt=""></a></li>
							</ul>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<script src="{% static 'js/jquery-3.3.1.min.js'%}"></script>
<script src="{% static 'styles/bootstrap4/popper.js'%}"></script>
<script src="{% static 'styles/bootstrap4/bootstrap.min.js' %}"></script>
<script src="{% static 'plugins/greensock/TweenMax.min.js' %}"></script>
<script src="{% static 'plugins/greensock/TimelineMax.min.js' %}"></script>
<script src="{% static 'plugins/scrollmagic/ScrollMagic.min.js' %}"></script>
<script src="{% static 'plugins/greensock/animation.gsap.min.js' %}"></script>
<script src="{% static 'plugins/greensock/ScrollToPlugin.min.js'%}"></script>
<script src="{% static 'plugins/easing/easing.js' %}"></script>
<script src="{% static 'js/cart_custom.js' %}"></script>

<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-23581568-13"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-23581568-13');
</script>

</body>


</html>

templates/orders.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="utf-8">
    <title>Proplex.kz</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <link rel="icon" type="image/png" href="{% static 'img/proplex_logo.png' %}">
    <meta content="Free HTML Templates" name="keywords">
    <meta content="Free HTML Templates" name="description">
    <script src="{% static 'js/jquery-3.5.1.js' %}" ></script>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link href="{% static 'css/style4.css'%}" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/newstyle.css' %}">
    <link rel="stylesheet" id="electro-style-css" href="https://electro.madrasthemes.com/wp-content/themes/electro/style.min.css?ver=3.3.0" type="text/css" media="all">
<style>
    .imgg{
        height: 50px;
    }
</style>
</head>

<body>
    {% include "navbar.html" %}
    <div id="content" class="site-content" tabindex="-1">
        <div class="container">
        <nav class="woocommerce-breadcrumb"><a style="color: black" href="/">Home</a><span class="delimiter"><i class="fa fa-angle-right"></i></span><a style="color: black" href="{% url 'core:profile' %}">My Account</a><span class="delimiter"><i class="fa fa-angle-right"></i></span><a style="color: black" href="{% url 'core:orders' %}">My Orders</a></nav><div class="site-content-inner row">
        </div>
        </div>
    <div class="container-fluid">
        <div class="row px-xl-5">
            <div class="col-lg-12 col-md-12 col-12">
                <div class="row pb-3">
                    <table class="table">
                        <thead>
                        <tr>
                            <th scope="col"></th>
                            <th scope="col">Order Id</th>
                            <th scope="col">Items</th>
                            <th scope="col">Prices</th>
                        </tr>
                        </thead>
                        {% for order in orders %}
                        <tr style="width: 100%">
                            <th scope="row">{{ forloop.counter }}</th>
                            <td>
                                <a>#{{ order.id }}</a>
                            </td>
                            <td>
                                <div class="py-4" style="word-break: break-word; ">
                                    {% for item in order.items.all %}
                                    <p class="h6" style=" width: 120px;font-size: 12px; word-break: break-word;">{{ item }}</p>
                                    {% endfor %}
                                </div>
                            </td>
                            <td>
                                <div>
                                    <h6>{{ order.get_total }}₸</h6>
                                </div>
                            </td>
                        </tr>
                        <tr>
{#                            <td colspan="5">#}
{#                                <a style="border-radius: 15px; color: dodgerblue; font-size: 10px" class="btn btn-outline-dark float-right ml-2" href='/checkout/'>Оформить заказ</a>#}
{#                                <a style="border-radius: 15px; color: dodgerblue; font-size: 10px" class="btn btn-outline-dark float-right ml-2" href='/'>Вернуться к товарам</a>#}
{#                                <a style="border-radius: 15px; color: orangered; font-size: 10px" class="btn btn-outline-dark float-right ml-2" href='/order-clear'>Очистить корзину</a>#}
{#                            </td>#}
                        </tr>
{#                        {% endif %}#}
                        {% endfor %}
                    </table>
                </div>
            </div>
        </div>
    </div>
</body>
{% include "footer.html" %}

templates/scripts.html
{% load static %}
<script type="text/javascript" src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
<!-- Bootstrap tooltips -->
<script type="text/javascript" src="{% static 'js/popper.min.js' %}"></script>
<!-- Bootstrap core JavaScript -->
<script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
<!-- MDB core JavaScript -->
<script type="text/javascript" src="{% static 'js/mdb.min.js' %}"></script>
<!-- Initializations -->
<script type="text/javascript">
  // Animations initialization
  new WOW().init();

</script>

templates/upload.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form method="POST" enctype="multipart/form-data" class="form-horizontal">
{% csrf_token %}
<div class="form-group">
    <label for="name" class="col-md-3 col-sm-3 col-xs-12 control-label">File: </label>
    <div class="col-md-8">
        <input type="file" name="csv_file" id="csv_file" required="True" class="form-control">
    </div>
</div>
<div class="form-group">
    <div class="col-md-3 col-sm-3 col-xs-12 col-md-offset-3" style="margin-bottom:10px;">
         <button class="btn btn-primary"> <span class="glyphicon glyphicon-upload" style="margin-right:5px;"></span>Upload </button>
    </div>
</div>
</form>
</body>
</html>